### ISSUE TITLE
Error Running Tests

### ISSUE THREAD

**Issue by super3** [Storj/metatool#9]
I am probably doing something wrong on the test setup. Idea would be appreciated.

``````
C:\Users\work\AppData\Local\Programs\Python\Python35-32\python.exe "C:\Program Files (x86)\JetBrains\PyCharm 5.0.2\helpers\pycharm\utrunner.py" C:\Users\work\code\metatool\metatool\tests\ true
Testing started at 5:16 PM ...
Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm 5.0.2\helpers\pycharm\utrunner.py", line 118, in <module>
    modules = loadModulesFromFolderRec(a[0])
  File "C:\Program Files (x86)\JetBrains\PyCharm 5.0.2\helpers\pycharm\utrunner.py", line 66, in loadModulesFromFolderRec
    modules.append(loadSource(os.path.join(root, name)))
  File "C:\Program Files (x86)\JetBrains\PyCharm 5.0.2\helpers\pycharm\utrunner.py", line 41, in loadSource
    module = imp.load_source(moduleName, fileName)
  File "C:\Users\work\AppData\Local\Programs\Python\Python35-32\lib\imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\work\code\metatool\metatool\tests\test_metadisk_app.py", line 16, in <module>
    from metatool.tests.testing_server import MyRequestHandler, ThreadedTCPServer
ImportError: No module named 'metatool.tests'

Process finished with exit code 1```
``````

**Comment by ViktorovEugene** [comment]
You was running the "tests" subpackage, which require loaded parent "metatool" package. Tests will started if you run the test of the entire "metatool" package. But I've fixed this bug and now you can run the tests both ways. Try the tests on updated version, it should work.
